### ISSUE TITLE
Need assistance testing?

### ISSUE THREAD

**Issue by doczong** [quavarus/Spotify.bundle#1]
Let me know if you would like me to test this bundle for you.  

I am tempted to branch it, but if you can provide me an auth code by way of your callback page, I will see how it works.  I have Roku, Android, PMP, and Web.

**Comment by quavarus** [comment]
Hey! Thanks for the offer. This is currently a non-functional work in progress. I'd be happy for any feedback once I get it up and running. I'll update this thread again when there is something worth looking at.

**Comment by jaddie** [comment]
What was the result of this, the project looks dead, perhaps would you like to create some issues / tasks on the project so we can all get to forking & collaborating on this?

**Comment by quavarus** [comment]
I'd say more comatose than dead :) Sorry about the lack of activity. I've had a semi working version for a while and wanted to knock out a few more bugs before pushing it. I got swamped with work and the holidays and everything, so this got pushed for a bit. 

I just pushed my initial working copy (bugs and all) so have fun!

**Comment by quavarus** [comment]
@doczong Getting back to the original question. I'd happily take any feedback and testing help. I have most of the devices you listed. The Roku would be a help. 

It pretty much goes for any device but ..
- If menu navigation doesn't work (you try to go into an album and instead of tracks you get that one album) Try disabling library mode in the plugin preferences and try again
- If you can navigate fine but get no sound try enabling "Transcode All" in the plugin preferences and try again
- Sometimes it can take a number of seconds (I've seen 10+) for playback to start. 
- The plugin will show tracks that Spotify knows about but cannot play due to rights holder agreements, so make sure what you are playing is available in another Spotify client.

I'm going to close this issue. Feel free to open new ones with your findings.
